### ISSUE TITLE
SD 2020 missing column names

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/census-2020#12]
Minor thing but noticed SD final data [does not](https://github.com/alarm-redist/census-2020/blob/main/census-vest-2020/sd_2020_vtd.csv) have 2020 vote even though [it exists](https://github.com/alarm-redist/census-2020/tree/main/vest-2020/sd) in vest-2020. When I re-ran the code the VEST 2020 columns become blanks at this line 
https://github.com/alarm-redist/census-2020/blob/4edefa39182156f14c5f85ebfaad2a722babcb69/R/00_build_vest.R#L98

which lead them to it being dropped in the census-2020 output.

**Comment by christopherkenny** [comment]
Oh, that just means you have an out-of-date PL94171. Something changed in the dplyr world a few months back that broke names in the retally. That's been fixed.

I think the actual issue was that we had not run the compile script. Should be fixed now in: https://github.com/alarm-redist/census-2020/commit/0ee10ef0779a0368844249f43e676405741dfd2e

**Comment by kuriwaki** [comment]
ok. Thanks for updating the data too!
