### ISSUE TITLE
Blocks with zero population in California

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/census-2020#9]
About 25 percent of rows in the CA data have 0 population. 11 percent of rows have 0 population _and_ 0 election vote tallies. Every CA county has these zero blocks to some extent.   What should we make of these blocks? 

``` r
suppressPackageStartupMessages(library(dplyr))
library(readr)


gh_url <- "https://github.com/alarm-redist/census-2020/raw/main/"
ca_alarm <- read_csv(paste0(gh_url, "census-vest-2020/ca_2020_block.csv"),
                     show_col_types = FALSE)

nrow(ca_alarm) # total rows
#> [1] 519723

sum(ca_alarm$pop == 0) # rows with 0 population
#> [1] 142132
sum(ca_alarm$vap == 0) # rows with 0 vap
#> [1] 144154

# row number of rows with no pres data
no_pres_rows <- which(with(ca_alarm, (pre_16_rep_tru == 0 & pre_16_dem_cli == 0 &  pre_20_rep_tru == 0 & pre_20_dem_bid == 0)))
length(no_pres_rows) # rows with no election data
#> [1] 187930

sum(ca_alarm$pop[no_pres_rows] == 0) # rows with no election data AND no population
#> [1] 59249
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Oregon and Hawaii also have similar zero pop blocks, though to a lesser extent.

**Comment by rootsmusic** [comment]
I don't know if you've already checked VEST's data, which RDH is beginning to validate.  You can run RDH's [Jupyter notebook for VEST's Hawaii data](https://github.com/nonpartisan-redistricting-datahub/pdv-hi/blob/main/vest-hi-2020/vest_hi_2020.ipynb).  By the way, you can [volunteer, apply for a job or a paid fellowship](https://redistrictingdatahub.org/engage/#workwithus) with RDH.

**Comment by christopherkenny** [comment]
Yeah, zero population blocks are blocks that have no people living in them by the 2020 Census count +- noise. I don't think there's actually any hidden meaning there.

As for blocks that have election data but zero population, that's introduced by the estimation across geographies. Some blocks crosswalk into new blocks that now we measures as having zero population. This is a simple estimation strategy without constraints on that. Perhaps there's an additional step to be taken to zero out zero population blocks and make sure that those votes are otherwise allocated. Thoughts @CoryMcCartan? 

I think we intended the blocks to be a stepping stone for 2020 geographies, but CA, OR, and HI do not appear to have Census Bureau VTDs, so we just report the estimated data at the block level with no aggregation.

**Comment by CoryMcCartan** [comment]
I think this is mostly population changes + DAS noise

**Comment by kuriwaki** [comment]
I see. I didn't realize there were so many blocks with 0 population (USCB said 2 million blocks with 0 pop in 2010!). It would be great to somehow aggregate those three states to precincts but that's for another issue.
